from __future__ import annotations

import json
from datetime import datetime, time
from pathlib import Path
from zoneinfo import ZoneInfo

import pytest

from production_audit import audit, expected_latest_draw
from reconcile_live_canonical import build_payload


# These analytics are intentionally regenerated by release_check.sh *after*
# pytest.  Their committed copies may therefore reflect the previous production
# run.  The final post-build production_audit.py --strict remains authoritative.
POST_BUILD_ONLY_PATHS = {
    "data/statistical_signal/predict_next_loto_stat_all.csv",
    "data/statistical_signal/predict_next_de_stat_all.csv",
    "data/number_dynamics/current_dynamics_loto.csv",
    "data/number_dynamics/current_dynamics_de.csv",
    "data/number_dynamics/diagnostics_loto.json",
    "data/number_dynamics/diagnostics_de.json",
    "data/advanced/conditional_matrices_diagnostics.json",
    "data/advanced/ai_ml_signal_diagnostics.json",
    "data/advanced/ai_ml_signal_loto.csv",
    "data/advanced/ai_ml_signal_de.csv",
    "data/ai_ml/cau_keo_manifest_loto.json",
    "data/ai_ml/cau_keo_manifest_de.json",
}
POST_BUILD_ONLY_PREFIXES = (
    "stat_signal_loto_target=",
    "stat_signal_de_target=",
    "cau_keo_loto_target=",
    "cau_keo_de_target=",
    "cau_keo_loto_calendar_contract_missing",
    "cau_keo_de_calendar_contract_missing",
    "conditional_",
    "ai_overlay_",
    "dynamics_loto_calendar_not_verified",
    "dynamics_de_calendar_not_verified",
    "dynamics_loto_anchor=",
    "dynamics_de_anchor=",
)


def test_expected_latest_draw_is_cutoff_aware():
    tz = ZoneInfo("Asia/Ho_Chi_Minh")
    assert expected_latest_draw(datetime(2026, 9, 1, 10, 0, tzinfo=tz), time(18, 15)).isoformat() == "2026-08-31"
    assert expected_latest_draw(datetime(2026, 9, 1, 19, 0, tzinfo=tz), time(18, 15)).isoformat() == "2026-09-01"


def test_reconcile_live_uses_only_accepted_canonical(tmp_path: Path):
    canonical = tmp_path / "xsmb.csv"
    fields = [
        "date", "special", "prize1", "prize2_1", "prize2_2",
        "prize3_1", "prize3_2", "prize3_3", "prize3_4", "prize3_5", "prize3_6",
        "prize4_1", "prize4_2", "prize4_3", "prize4_4",
        "prize5_1", "prize5_2", "prize5_3", "prize5_4", "prize5_5", "prize5_6",
        "prize6_1", "prize6_2", "prize6_3",
        "prize7_1", "prize7_2", "prize7_3", "prize7_4",
    ]
    values = ["2026-08-31", "35644", "44080"] + [str(10000 + i) for i in range(2)] + [str(20000 + i) for i in range(6)] + [str(3000 + i) for i in range(4)] + [str(4000 + i) for i in range(6)] + [str(500 + i) for i in range(3)] + [str(60 + i) for i in range(4)]
    canonical.write_text(",".join(fields) + "\n" + ",".join(values) + "\n", encoding="utf-8")

    audit_path = tmp_path / "audit.json"
    audit_path.write_text(
        json.dumps(
            {
                "2026-08-31": {
                    "accepted": True,
                    "agreement": 4,
                    "source_agreement": 5,
                    "independent_groups": ["xoso", "mketqua", "minhngoc", "xosodaiphat"],
                    "sources": ["xoso.com.vn", "mketqua.net"],
                }
            }
        ),
        encoding="utf-8",
    )

    payload = build_payload(canonical=canonical, audit_path=audit_path)
    assert payload["draw_date"] == "2026-08-31"
    assert payload["status"] == "complete_verified"
    assert payload["verified_complete"] is True
    assert payload["canonical_reconciled"] is True
    assert payload["received_values"] == 27
    assert payload["prizes"]["special"] == ["35644"]
    assert sum(len(v) for v in payload["prizes"].values()) == 27


@pytest.mark.parametrize("unsafe_value", ["12.5", "NaN", "<script>", "１２３４５"])
def test_reconcile_live_rejects_noncanonical_prize_values(
    tmp_path: Path, unsafe_value: str
) -> None:
    canonical = tmp_path / "xsmb.csv"
    canonical.write_text(
        "date,special\n2026-08-31," + unsafe_value + "\n", encoding="utf-8"
    )
    audit_path = tmp_path / "audit.json"
    audit_path.write_text(
        json.dumps(
            {
                "2026-08-31": {
                    "accepted": True,
                    "agreement": 2,
                    "sources": ["xoso.com.vn", "mketqua.net"],
                }
            }
        ),
        encoding="utf-8",
    )

    with pytest.raises((KeyError, ValueError)):
        build_payload(canonical=canonical, audit_path=audit_path)


def _prebuild_critical(critical: list[str]) -> list[str]:
    """Exclude only analytics that release_check deliberately builds after pytest.

    Core/canonical/model/history failures remain visible here.  Generated analytics
    are validated later in the same release_check by explicit assertions and by
    the final strict production audit, so no release condition is waived.
    """
    out: list[str] = []
    for item in critical:
        if item.startswith("missing_or_empty="):
            paths = item.split("=", 1)[1].split(",")
            remaining = [p for p in paths if p not in POST_BUILD_ONLY_PATHS]
            if remaining:
                out.append("missing_or_empty=" + ",".join(remaining))
            continue
        if item.startswith(POST_BUILD_ONLY_PREFIXES):
            continue
        out.append(item)
    return out


def test_current_repo_data_and_models_are_internally_consistent():
    result = audit(check_freshness=False, check_docs=False)
    critical = _prebuild_critical(result["critical"])
    assert not critical, critical


def test_prebuild_filter_covers_only_regenerated_analytics():
    critical = _prebuild_critical(
        [
            "missing_or_empty=data/advanced/ai_ml_signal_diagnostics.json,data/xsmb.csv",
            "conditional_diagnostics_invalid=not built yet",
            "cau_keo_loto_calendar_contract_missing",
            "dynamics_de_calendar_not_verified",
            "stat_signal_loto_target=2026-08-31 expected=2026-09-01",
            "source_consensus_lt2=2026-09-01",
            "health_json_not_ok",
        ]
    )
    assert critical == [
        "missing_or_empty=data/xsmb.csv",
        "source_consensus_lt2=2026-09-01",
        "health_json_not_ok",
    ]


def test_watchdog_and_post_finalization_workflows_are_wired():
    watchdog = Path(".github/workflows/watchdog.yml").read_text(encoding="utf-8")
    post = Path(".github/workflows/post-finalization.yml").read_text(encoding="utf-8")
    daily = Path(".github/workflows/update-data.yml").read_text(encoding="utf-8")

    for cron in ("10 11 * * *", "20 11 * * *", "35 12 * * *", "5 13 * * *", "20 13 * * *", "15 0 * * *"):
        assert cron in watchdog
    assert 'dispatch("live-results.yml")' in watchdog
    assert 'dispatch("update-data.yml")' in watchdog
    assert 'dispatch("pages.yml")' in watchdog
    assert 'dispatch("post-finalization.yml")' in watchdog

    # Deterministic primary path: a successful daily run explicitly dispatches
    # post-finalization; watchdog remains an independent fallback.
    assert "actions: write" in daily
    assert "canonical_ready" in daily
    assert "trigger-post-finalization:" in daily
    assert "post-finalization.yml/dispatches" in daily

    # Do not rely on workflow_run for the primary hand-off; newly introduced
    # workflow_run triggers can miss the same commit's already-started run.
    assert "workflow_run:" not in post
    assert "workflow_dispatch:" in post
    assert "src/production_audit.py" in post
    assert "src/reconcile_live_canonical.py" in post
    assert "/tmp/live-canonical.json" not in post
    assert "mktemp" in post

    assert "/tmp/production_audit.json" not in watchdog
    assert "TemporaryDirectory" in watchdog

    live = Path(".github/workflows/live-results.yml").read_text(encoding="utf-8")
    assert "/tmp/live.json" not in live
    assert "mktemp" in live
