from __future__ import annotations

"""Canonical two-digit number ontology for VLA.

This module is a terminology/combinatorics contract, not a claim of predictive
power.  It keeps folklore/domain relations explicit so that statistical models
can test them instead of silently conflating different meanings of "cặp",
"bộ", "bóng", "lộn" and "kép".

Production/domain conventions:
- bóng dương digit: 0↔5, 1↔6, 2↔7, 3↔8, 4↔9;
- bóng âm digit (documented folklore convention):
  0↔7, 1↔4, 2↔9, 3↔6, 5↔8;
- lộn/reverse: AB ↔ BA;
- bộ/hệ: orbit generated by digit-wise bóng dương plus lộn;
- the 00..99 universe contains 15 unique bộ families: 10 regular families of
  8 numbers and 5 bộ kép families of 4 numbers;
- the common 50-cặp-loto partition contains 45 reverse pairs AB↔BA plus five
  kép-bóng pairs: 00↔55, 11↔66, 22↔77, 33↔88, 44↔99;
- same-draw co-occurrence remains a statistical relation and is not a synonym
  for any deterministic pair family.
"""

from functools import lru_cache
from numbers import Integral

ONTOLOGY_SCHEMA_VERSION = 3

BONG_DUONG: dict[int, int] = {
    0: 5,
    1: 6,
    2: 7,
    3: 8,
    4: 9,
    5: 0,
    6: 1,
    7: 2,
    8: 3,
    9: 4,
}

BONG_AM: dict[int, int] = {
    0: 7,
    7: 0,
    1: 4,
    4: 1,
    2: 9,
    9: 2,
    3: 6,
    6: 3,
    5: 8,
    8: 5,
}

# Backward-compatible alias. New code should prefer BONG_DUONG / bong_duong().
BONG = BONG_DUONG


def normalize_two_digit(value: int | str) -> str:
    """Normalize an integer-like value into exact 00..99 text."""

    if isinstance(value, bool):
        raise ValueError(f"Invalid two-digit value: {value!r}")
    if isinstance(value, str):
        raw = value.strip()
        if not raw or not raw.isascii() or not raw.isdigit():
            raise ValueError(f"Invalid two-digit value: {value!r}")
        n = int(raw)
    elif isinstance(value, Integral):
        n = int(value)
    else:
        raise ValueError(f"Invalid two-digit value: {value!r}")
    if not 0 <= n <= 99:
        raise ValueError(f"Two-digit value outside 00..99: {value!r}")
    return f"{n:02d}"


def _digit(value: int) -> int:
    if isinstance(value, bool) or not isinstance(value, Integral):
        raise ValueError(f"Digit outside 0..9: {value!r}")
    n = int(value)
    if not 0 <= n <= 9:
        raise ValueError(f"Digit outside 0..9: {value!r}")
    return n


def head(value: int | str) -> int:
    return int(normalize_two_digit(value)[0])


def tail(value: int | str) -> int:
    return int(normalize_two_digit(value)[1])


def digit_sum(value: int | str) -> int:
    s = normalize_two_digit(value)
    return int(s[0]) + int(s[1])


def digit_sum_mod10(value: int | str) -> int:
    return digit_sum(value) % 10


def reverse(value: int | str) -> str:
    """Lộn/đảo AB → BA."""

    return normalize_two_digit(value)[::-1]


lon = reverse


def bong_duong_digit(value: int) -> int:
    return BONG_DUONG[_digit(value)]


def bong_digit(value: int) -> int:
    """Backward-compatible alias for bóng dương digit."""

    return bong_duong_digit(value)


def bong_duong(value: int | str) -> str:
    s = normalize_two_digit(value)
    return f"{BONG_DUONG[int(s[0])]}{BONG_DUONG[int(s[1])]}"


def bong(value: int | str) -> str:
    """Backward-compatible alias for canonical bóng dương."""

    return bong_duong(value)


def bong_am_digit(value: int) -> int:
    return BONG_AM[_digit(value)]


def bong_am(value: int | str) -> str:
    s = normalize_two_digit(value)
    return f"{BONG_AM[int(s[0])]}{BONG_AM[int(s[1])]}"


def cap_bong_duong(value: int | str) -> frozenset[str]:
    s = normalize_two_digit(value)
    return frozenset({s, bong_duong(s)})


def cap_bong_am(value: int | str) -> frozenset[str]:
    s = normalize_two_digit(value)
    return frozenset({s, bong_am(s)})


def complement9_digit(value: int) -> int:
    """Mathematical 9-complement, deliberately not called bóng."""

    return 9 - _digit(value)


def complement9(value: int | str) -> str:
    s = normalize_two_digit(value)
    return f"{9 - int(s[0])}{9 - int(s[1])}"


@lru_cache(maxsize=100)
def bo(value: int | str) -> frozenset[str]:
    """Canonical bóng-dương/lộn family containing ``value``.

    Families contain 4 or 8 unique numbers. The minimum member is also the
    conventional family label for the 15-family system: 00,01,02,03,04,11,12,
    13,14,22,23,24,33,34,44.
    """

    s = normalize_two_digit(value)
    x, y = int(s[0]), int(s[1])
    xs = {x, BONG_DUONG[x]}
    ys = {y, BONG_DUONG[y]}
    out: set[str] = set()
    for a in xs:
        for b in ys:
            out.add(f"{a}{b}")
            out.add(f"{b}{a}")
    return frozenset(out)


def bo_seed_label(value: int | str) -> str:
    return normalize_two_digit(value)


def bo_family_id(value: int | str) -> str:
    return min(bo(value))


def bo_family_kind(value: int | str) -> str:
    return "bo_kep" if len(bo(value)) == 4 else "bo_thuong"


def all_bo() -> tuple[frozenset[str], ...]:
    families = {bo(i) for i in range(100)}
    return tuple(sorted(families, key=lambda group: (min(group), len(group))))


def bo_seed_catalog() -> tuple[dict[str, object], ...]:
    rows: list[dict[str, object]] = []
    for n in range(100):
        seed = f"{n:02d}"
        members = tuple(sorted(bo(seed)))
        rows.append(
            {
                "seed_label": seed,
                "canonical_family_id": min(members),
                "family_kind": "bo_kep" if len(members) == 4 else "bo_thuong",
                "family_size": len(members),
                "members": members,
            }
        )
    return tuple(rows)


def unique_bo_catalog() -> tuple[dict[str, object], ...]:
    rows: list[dict[str, object]] = []
    for family in all_bo():
        members = tuple(sorted(family))
        rows.append(
            {
                "canonical_family_id": members[0],
                "family_kind": "bo_kep" if len(members) == 4 else "bo_thuong",
                "family_size": len(members),
                "members": members,
                "seed_labels": tuple(
                    f"{n:02d}" for n in range(100) if bo_family_id(n) == members[0]
                ),
            }
        )
    return tuple(rows)


def cap_lon(value: int | str) -> frozenset[str]:
    """Cặp lộn AB↔BA; doubles alone are singleton reverse orbits."""

    s = normalize_two_digit(value)
    return frozenset({s, reverse(s)})


def is_kep_bang(value: int | str) -> bool:
    s = normalize_two_digit(value)
    return s[0] == s[1]


def cap_loto_50_partner(value: int | str) -> str:
    """Partner in the common 50-cặp-loto partition.

    Non-doubles pair with their reverse. Kép bằng numbers pair with the bóng
    dương kép, giving exactly the five pairs 00-55, 11-66, 22-77, 33-88, 44-99.
    """

    s = normalize_two_digit(value)
    return bong_duong(s) if is_kep_bang(s) else reverse(s)


def cap_loto_50(value: int | str) -> frozenset[str]:
    s = normalize_two_digit(value)
    return frozenset({s, cap_loto_50_partner(s)})


def cap_loto_50_kind(value: int | str) -> str:
    return "kep_bong" if is_kep_bang(value) else "reverse"


def cap_loto_50_id(value: int | str) -> str:
    return "-".join(sorted(cap_loto_50(value)))


def all_cap_loto_50() -> tuple[frozenset[str], ...]:
    pairs = {cap_loto_50(i) for i in range(100)}
    return tuple(sorted(pairs, key=lambda p: tuple(sorted(p))))


def kep_bong_pairs() -> tuple[tuple[str, str], ...]:
    return tuple(
        tuple(sorted(cap_loto_50(f"{d}{d}")))  # type: ignore[arg-type]
        for d in range(5)
    )


def canonical_unordered_pair(
    a: int | str, b: int | str, *, allow_equal: bool = False
) -> tuple[str, str]:
    sa, sb = normalize_two_digit(a), normalize_two_digit(b)
    if sa == sb and not allow_equal:
        raise ValueError("unordered pair requires two distinct numbers")
    x, y = sorted((sa, sb))
    return x, y


def pair_key(a: int | str, b: int | str, *, allow_equal: bool = False) -> str:
    x, y = canonical_unordered_pair(a, b, allow_equal=allow_equal)
    return f"{x}-{y}"


def pair_relation_tags(a: int | str, b: int | str) -> tuple[str, ...]:
    sa, sb = normalize_two_digit(a), normalize_two_digit(b)
    tags: list[str] = []
    if sa == sb:
        tags.append("same_number")
    if reverse(sa) == sb and sa != sb:
        tags.append("reverse")
    if bong_duong(sa) == sb:
        tags.append("bong_duong")
    if bong_am(sa) == sb:
        tags.append("bong_am")
    if cap_loto_50_partner(sa) == sb:
        tags.append("cap_loto_50")
        if cap_loto_50_kind(sa) == "kep_bong":
            tags.append("kep_bong")
    if bo_family_id(sa) == bo_family_id(sb):
        tags.append("same_bo_family")
    return tuple(tags)


def dan_cham(digit: int) -> tuple[str, ...]:
    d = _digit(digit)
    return tuple(f"{n:02d}" for n in range(100) if d in (n // 10, n % 10))


def dan_dau(digit: int) -> tuple[str, ...]:
    d = _digit(digit)
    return tuple(f"{d}{x}" for x in range(10))


def dan_duoi(digit: int) -> tuple[str, ...]:
    d = _digit(digit)
    return tuple(f"{x}{d}" for x in range(10))


def dan_tong_mod10(total: int) -> tuple[str, ...]:
    d = _digit(total)
    return tuple(f"{n:02d}" for n in range(100) if digit_sum_mod10(n) == d)


def kep_bang() -> tuple[str, ...]:
    return tuple(f"{d}{d}" for d in range(10))


def kep_lech() -> tuple[str, ...]:
    """Kép lệch dương: digits are bóng dương, both orientations."""

    return tuple(f"{d}{BONG_DUONG[d]}" for d in range(10))


def kep_am() -> tuple[str, ...]:
    """Kép âm under the documented bóng-âm convention, both orientations."""

    return tuple(sorted({f"{d}{BONG_AM[d]}" for d in range(10)}))


def sat_kep() -> tuple[str, ...]:
    """Linear adjacent-digit variant; excludes circular 09/90."""

    return tuple(
        f"{a}{b}"
        for a in range(10)
        for b in range(10)
        if abs(a - b) == 1
    )


def sat_kep_vong() -> tuple[str, ...]:
    """Circular adjacent-digit variant, explicitly including 09/90."""

    return tuple(
        f"{a}{b}"
        for a in range(10)
        for b in range(10)
        if a != b and min((a - b) % 10, (b - a) % 10) == 1
    )


def classify_number(value: int | str) -> dict[str, object]:
    s = normalize_two_digit(value)
    family = tuple(sorted(bo(s)))
    partner = cap_loto_50_partner(s)
    return {
        "number": s,
        "head": head(s),
        "tail": tail(s),
        "reverse": reverse(s),
        "bong_duong": bong_duong(s),
        "bong_am": bong_am(s),
        "cap_loto_50_id": cap_loto_50_id(s),
        "cap_loto_50_kind": cap_loto_50_kind(s),
        "cap_loto_50_partner": partner,
        "bo_seed_label": s,
        "bo_family_id": family[0],
        "bo_family_kind": "bo_kep" if len(family) == 4 else "bo_thuong",
        "bo_family_size": len(family),
        "bo_members": family,
        "digit_sum": digit_sum(s),
        "sum_mod10": digit_sum_mod10(s),
        "is_kep_bang": s in set(kep_bang()),
        "is_kep_lech": s in set(kep_lech()),
        "is_kep_am": s in set(kep_am()),
        "is_sat_kep": s in set(sat_kep()),
        "is_sat_kep_vong": s in set(sat_kep_vong()),
    }


def validate_ontology() -> None:
    assert all(BONG_DUONG[BONG_DUONG[d]] == d for d in range(10))
    assert all(BONG_AM[BONG_AM[d]] == d for d in range(10))
    assert all(reverse(reverse(n)) == f"{n:02d}" for n in range(100))

    families = all_bo()
    assert len(families) == 15
    sizes = sorted(len(f) for f in families)
    assert sizes.count(4) == 5 and sizes.count(8) == 10
    flat = [member for family in families for member in family]
    assert len(flat) == 100 and len(set(flat)) == 100
    assert set(flat) == {f"{n:02d}" for n in range(100)}
    assert {min(f) for f in families} == {
        "00", "01", "02", "03", "04", "11", "12", "13", "14", "22",
        "23", "24", "33", "34", "44",
    }

    pairs = all_cap_loto_50()
    assert len(pairs) == 50
    assert all(len(p) == 2 for p in pairs)
    pair_flat = [n for pair in pairs for n in pair]
    assert len(pair_flat) == 100 and len(set(pair_flat)) == 100
    assert set(pair_flat) == {f"{n:02d}" for n in range(100)}
    assert sum(cap_loto_50_kind(min(p)) == "kep_bong" for p in pairs) == 5
    assert set(cap_loto_50_id(f"{d}{d}") for d in range(10)) == {
        "00-55", "11-66", "22-77", "33-88", "44-99"
    }

    assert set(kep_lech()) == {
        "05", "50", "16", "61", "27", "72", "38", "83", "49", "94"
    }
    assert set(kep_am()) == {
        "07", "70", "14", "41", "29", "92", "36", "63", "58", "85"
    }


def reference_catalog() -> dict[str, object]:
    validate_ontology()
    pairs = all_cap_loto_50()
    return {
        "schema_version": ONTOLOGY_SCHEMA_VERSION,
        "canonical_bong": "bong_duong",
        "bong_duong": {str(k): v for k, v in BONG_DUONG.items()},
        "bong_am": {
            "status": "documented_domain_convention",
            "mapping": {str(k): v for k, v in BONG_AM.items()},
            "predictive_status": "must_be_empirically_validated",
        },
        "bo_seed_label_count": 100,
        "bo_unique_family_count": len(all_bo()),
        "bo_family_size_distribution": {
            "4": sum(len(x) == 4 for x in all_bo()),
            "8": sum(len(x) == 8 for x in all_bo()),
        },
        "bo_family_kind_distribution": {"bo_kep": 5, "bo_thuong": 10},
        "cap_loto_50_count": len(pairs),
        "cap_loto_50_kind_distribution": {"reverse": 45, "kep_bong": 5},
        "kep_bong_pairs": ["-".join(p) for p in kep_bong_pairs()],
        "kep_bang": list(kep_bang()),
        "kep_lech": list(kep_lech()),
        "kep_am": list(kep_am()),
        "sat_kep": list(sat_kep()),
        "sat_kep_vong_research_variant": list(sat_kep_vong()),
        "touch_cardinality": {str(d): len(dan_cham(d)) for d in range(10)},
        "sum_mod10_cardinality": {
            str(d): len(dan_tong_mod10(d)) for d in range(10)
        },
        "pair_terms": {
            "generic_pair": "unordered pair of two distinct two-digit numbers",
            "cap_loto_50": "45 reverse pairs plus 5 kép-bóng pairs partitioning 00..99",
            "cap_lon": "deterministic AB↔BA relation",
            "kep_bong": "00↔55,11↔66,22↔77,33↔88,44↔99",
            "cap_bong_duong": "deterministic full-number bóng dương relation",
            "cap_bong_am": "documented folklore bóng-âm relation",
            "same_draw_cooccurrence": "statistical unordered pair observed in one draw",
            "same_bo_family": "two numbers belong to the same canonical bộ family",
        },
    }
