from __future__ import annotations

"""Canonical two-digit number ontology for VLA.

The purpose of this module is *terminology and deterministic combinatorics*, not
prediction. It keeps folklore labels separate from mathematical relations so
that "cặp", "bộ", "bóng", "lộn", "kép" and co-occurrence are not silently mixed.

Canonical conventions used by VLA:
- bóng dương digit: 0↔5, 1↔6, 2↔7, 3↔8, 4↔9;
- lộn/reverse: AB ↔ BA;
- bộ/hệ seed: family generated by bóng dương on each digit plus lộn;
- 100 seed labels exist, but they collapse to 15 unique canonical families;
- cặp lộn is a relation between a two-digit number and its reverse;
- a generic cặp số is an unordered pair and must not imply lộn/bóng;
- same-draw co-occurrence is a statistical pair and is NOT a synonym for cặp lộn;
- "bóng âm" is intentionally not hard-coded because public folklore definitions
  conflict; any such mapping must remain explicitly non-canonical/research-only.
"""

from functools import lru_cache
from numbers import Integral

ONTOLOGY_SCHEMA_VERSION = 2

BONG_DUONG: dict[int, int] = {
    0: 5,
    1: 6,
    2: 7,
    3: 8,
    4: 9,
    5: 0,
    6: 1,
    7: 2,
    8: 3,
    9: 4,
}

# Backward-compatible alias. New code should prefer BONG_DUONG / bong_duong().
BONG = BONG_DUONG


def normalize_two_digit(value: int | str) -> str:
    """Normalize an integer-like value into exact 00..99 text.

    Strings must contain ASCII decimal digits only. We do not repair dirty
    tokens by stripping arbitrary characters.
    """

    if isinstance(value, bool):
        raise ValueError(f"Invalid two-digit value: {value!r}")
    if isinstance(value, str):
        raw = value.strip()
        if not raw or not raw.isascii() or not raw.isdigit():
            raise ValueError(f"Invalid two-digit value: {value!r}")
        n = int(raw)
    elif isinstance(value, Integral):
        n = int(value)
    else:
        raise ValueError(f"Invalid two-digit value: {value!r}")
    if not 0 <= n <= 99:
        raise ValueError(f"Two-digit value outside 00..99: {value!r}")
    return f"{n:02d}"


def _digit(value: int) -> int:
    if isinstance(value, bool) or not isinstance(value, Integral):
        raise ValueError(f"Digit outside 0..9: {value!r}")
    n = int(value)
    if not 0 <= n <= 9:
        raise ValueError(f"Digit outside 0..9: {value!r}")
    return n


def head(value: int | str) -> int:
    return int(normalize_two_digit(value)[0])


def tail(value: int | str) -> int:
    return int(normalize_two_digit(value)[1])


def digit_sum(value: int | str) -> int:
    s = normalize_two_digit(value)
    return int(s[0]) + int(s[1])


def digit_sum_mod10(value: int | str) -> int:
    return digit_sum(value) % 10


def reverse(value: int | str) -> str:
    """Lộn/đảo AB → BA."""

    return normalize_two_digit(value)[::-1]


# Vietnamese-domain alias, kept explicit for readability in reports.
lon = reverse


def bong_duong_digit(value: int) -> int:
    return BONG_DUONG[_digit(value)]


def bong_digit(value: int) -> int:
    """Backward-compatible alias for bóng dương digit."""

    return bong_duong_digit(value)


def bong_duong(value: int | str) -> str:
    s = normalize_two_digit(value)
    return f"{BONG_DUONG[int(s[0])]}{BONG_DUONG[int(s[1])]}"


def bong(value: int | str) -> str:
    """Backward-compatible alias for the canonical bóng dương mapping."""

    return bong_duong(value)


def cap_bong_duong(value: int | str) -> frozenset[str]:
    """Two-number bóng dương relation for one 2D number."""

    s = normalize_two_digit(value)
    return frozenset({s, bong_duong(s)})


def complement9_digit(value: int) -> int:
    """Mathematical 9-complement, deliberately *not* called bóng."""

    return 9 - _digit(value)


def complement9(value: int | str) -> str:
    s = normalize_two_digit(value)
    return f"{9 - int(s[0])}{9 - int(s[1])}"


@lru_cache(maxsize=100)
def bo(value: int | str) -> frozenset[str]:
    """Return the canonical bóng-dương/lộn family containing ``value``.

    This is the orbit generated by applying bóng dương independently to either
    digit and allowing digit reversal. A family contains 4 or 8 unique numbers.
    Seed labels 00..99 are *not* unique families: many labels refer to the same
    canonical family.
    """

    s = normalize_two_digit(value)
    x, y = int(s[0]), int(s[1])
    xs = {x, BONG_DUONG[x]}
    ys = {y, BONG_DUONG[y]}
    out: set[str] = set()
    for a in xs:
        for b in ys:
            out.add(f"{a}{b}")
            out.add(f"{b}{a}")
    return frozenset(out)


def bo_seed_label(value: int | str) -> str:
    """Return the historical 00..99 seed label, without claiming uniqueness."""

    return normalize_two_digit(value)


def bo_family_id(value: int | str) -> str:
    """Stable ID for the unique canonical family: smallest member."""

    return min(bo(value))


def all_bo() -> tuple[frozenset[str], ...]:
    """Return the 15 unique canonical families that partition 00..99."""

    families = {bo(i) for i in range(100)}
    return tuple(sorted(families, key=lambda group: (min(group), len(group))))


def bo_seed_catalog() -> tuple[dict[str, object], ...]:
    """Return all 100 historical seed labels mapped to canonical family IDs."""

    rows: list[dict[str, object]] = []
    for n in range(100):
        seed = f"{n:02d}"
        members = tuple(sorted(bo(seed)))
        rows.append(
            {
                "seed_label": seed,
                "canonical_family_id": min(members),
                "family_size": len(members),
                "members": members,
            }
        )
    return tuple(rows)


def unique_bo_catalog() -> tuple[dict[str, object], ...]:
    rows: list[dict[str, object]] = []
    for family in all_bo():
        members = tuple(sorted(family))
        rows.append(
            {
                "canonical_family_id": members[0],
                "family_size": len(members),
                "members": members,
                "seed_labels": tuple(
                    f"{n:02d}" for n in range(100) if bo_family_id(n) == members[0]
                ),
            }
        )
    return tuple(rows)


def cap_lon(value: int | str) -> frozenset[str]:
    """Cặp lộn/đảo of a number; doubles contain one unique member."""

    s = normalize_two_digit(value)
    return frozenset({s, reverse(s)})


def canonical_unordered_pair(
    a: int | str, b: int | str, *, allow_equal: bool = False
) -> tuple[str, str]:
    """Canonical key for a generic/statistical unordered pair of 2D numbers."""

    sa, sb = normalize_two_digit(a), normalize_two_digit(b)
    if sa == sb and not allow_equal:
        raise ValueError("unordered pair requires two distinct numbers")
    x, y = sorted((sa, sb))
    return x, y


def pair_key(a: int | str, b: int | str, *, allow_equal: bool = False) -> str:
    x, y = canonical_unordered_pair(a, b, allow_equal=allow_equal)
    return f"{x}-{y}"


def pair_relation_tags(a: int | str, b: int | str) -> tuple[str, ...]:
    """Describe deterministic relationships without conflating co-occurrence."""

    sa, sb = normalize_two_digit(a), normalize_two_digit(b)
    tags: list[str] = []
    if sa == sb:
        tags.append("same_number")
    if reverse(sa) == sb and sa != sb:
        tags.append("reverse")
    if bong_duong(sa) == sb:
        tags.append("bong_duong")
    if bo_family_id(sa) == bo_family_id(sb):
        tags.append("same_bo_family")
    return tuple(tags)


def dan_cham(digit: int) -> tuple[str, ...]:
    d = _digit(digit)
    return tuple(f"{n:02d}" for n in range(100) if d in (n // 10, n % 10))


def dan_dau(digit: int) -> tuple[str, ...]:
    d = _digit(digit)
    return tuple(f"{d}{x}" for x in range(10))


def dan_duoi(digit: int) -> tuple[str, ...]:
    d = _digit(digit)
    return tuple(f"{x}{d}" for x in range(10))


def dan_tong_mod10(total: int) -> tuple[str, ...]:
    d = _digit(total)
    return tuple(f"{n:02d}" for n in range(100) if digit_sum_mod10(n) == d)


def kep_bang() -> tuple[str, ...]:
    """Kép bằng: 00, 11, ..., 99."""

    return tuple(f"{d}{d}" for d in range(10))


def kep_lech() -> tuple[str, ...]:
    """Kép lệch dương: digits paired by bóng dương, both orientations."""

    return tuple(f"{d}{BONG_DUONG[d]}" for d in range(10))


def sat_kep() -> tuple[str, ...]:
    """Sát kép linear: two different adjacent digits; no circular 09/90 wrap."""

    return tuple(
        f"{a}{b}"
        for a in range(10)
        for b in range(10)
        if abs(a - b) == 1
    )


def sat_kep_vong() -> tuple[str, ...]:
    """Circular-adjacent research variant, explicitly including 09 and 90."""

    return tuple(
        f"{a}{b}"
        for a in range(10)
        for b in range(10)
        if a != b and min((a - b) % 10, (b - a) % 10) == 1
    )


def classify_number(value: int | str) -> dict[str, object]:
    s = normalize_two_digit(value)
    family = tuple(sorted(bo(s)))
    kep_bang_set = set(kep_bang())
    kep_lech_set = set(kep_lech())
    sat_kep_set = set(sat_kep())
    sat_kep_vong_set = set(sat_kep_vong())
    return {
        "number": s,
        "head": head(s),
        "tail": tail(s),
        "reverse": reverse(s),
        "bong_duong": bong_duong(s),
        "bo_seed_label": s,
        "bo_family_id": family[0],
        "bo_family_size": len(family),
        "bo_members": family,
        "digit_sum": digit_sum(s),
        "sum_mod10": digit_sum_mod10(s),
        "is_kep_bang": s in kep_bang_set,
        "is_kep_lech": s in kep_lech_set,
        "is_sat_kep": s in sat_kep_set,
        "is_sat_kep_vong": s in sat_kep_vong_set,
    }


def validate_ontology() -> None:
    """Fail fast if the core deterministic ontology stops being a partition."""

    assert all(BONG_DUONG[BONG_DUONG[d]] == d for d in range(10))
    assert all(reverse(reverse(n)) == f"{n:02d}" for n in range(100))
    families = all_bo()
    assert len(families) == 15
    sizes = sorted(len(f) for f in families)
    assert sizes.count(4) == 5 and sizes.count(8) == 10
    flat = [member for family in families for member in family]
    assert len(flat) == 100 and len(set(flat)) == 100
    assert set(flat) == {f"{n:02d}" for n in range(100)}
    assert set(kep_lech()) == {
        "05",
        "50",
        "16",
        "61",
        "27",
        "72",
        "38",
        "83",
        "49",
        "94",
    }


def reference_catalog() -> dict[str, object]:
    validate_ontology()
    return {
        "schema_version": ONTOLOGY_SCHEMA_VERSION,
        "canonical_bong": "bong_duong",
        "bong_duong": {str(k): v for k, v in BONG_DUONG.items()},
        "bong_am": {
            "status": "non_canonical",
            "reason": "public folklore mappings conflict; not used by production logic",
        },
        "bo_seed_label_count": 100,
        "bo_unique_family_count": len(all_bo()),
        "bo_family_size_distribution": {
            "4": sum(len(x) == 4 for x in all_bo()),
            "8": sum(len(x) == 8 for x in all_bo()),
        },
        "kep_bang": list(kep_bang()),
        "kep_lech": list(kep_lech()),
        "sat_kep": list(sat_kep()),
        "sat_kep_vong_research_variant": list(sat_kep_vong()),
        "touch_cardinality": {str(d): len(dan_cham(d)) for d in range(10)},
        "sum_mod10_cardinality": {
            str(d): len(dan_tong_mod10(d)) for d in range(10)
        },
        "pair_terms": {
            "generic_pair": "unordered pair of two distinct two-digit numbers",
            "cap_lon": "deterministic AB↔BA relation",
            "cap_bong_duong": "deterministic full-number bóng dương relation",
            "same_draw_cooccurrence": "statistical unordered pair observed in one draw",
            "same_bo_family": "two numbers belong to the same canonical bộ family",
        },
    }
