from __future__ import annotations

from dataclasses import dataclass
from datetime import date, timedelta
from typing import Literal, Optional

import numpy as np
import pandas as pd

from path_models import (
    PathParams,
    build_daily_targets,
    build_rawdata_digits_from_row,
    enumerate_position_pairs,
    get_scope_indices,
)

Mode = Literal["loto", "de"]
FilterKind = Literal["stable", "active"]


@dataclass
class PathStats:
    lag: int
    i: int
    j: int
    trials: int
    hits: int
    p_mean: float
    max_streak: int
    current_streak: int
    special_touch: int
    special_both: int


def _resolve_anchor_index(dates: list[date], anchor_date: Optional[date]) -> int:
    if anchor_date is None:
        return len(dates) - 1
    try:
        return dates.index(anchor_date)
    except ValueError as exc:
        raise ValueError(f"anchor_date {anchor_date} not found in dataset") from exc


def _streak_stats(hit_matrix: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    """Vector-friendly max/current streaks for shape (trials, rules)."""
    if hit_matrix.size == 0:
        n_rules = hit_matrix.shape[1] if hit_matrix.ndim == 2 else 0
        z = np.zeros(n_rules, dtype=np.int16)
        return z, z.copy()

    n_rules = hit_matrix.shape[1]
    cur = np.zeros(n_rules, dtype=np.int16)
    max_streak = np.zeros(n_rules, dtype=np.int16)
    for row in hit_matrix:
        cur = np.where(row, cur + 1, 0).astype(np.int16, copy=False)
        max_streak = np.maximum(max_streak, cur)
    return max_streak, cur


def _select_rule_indices(
    *,
    p_mean: np.ndarray,
    hits: np.ndarray,
    max_streak: np.ndarray,
    current_streak: np.ndarray,
    params: PathParams,
    mode: Mode,
) -> np.ndarray:
    """Keep only statistically relevant path rules for a lag.

    The legacy implementation retained every position pair for every lag, even
    though only active/stable rules are used downstream.  Keeping a bounded set
    prevents quadratic repository/runtime growth while preserving the strongest
    rules under both current-streak and historical-streak criteria.
    """
    eligible = (current_streak >= params.min_current_streak) | (max_streak >= params.min_max_streak)
    idx = np.flatnonzero(eligible)
    if idx.size == 0:
        idx = np.arange(len(p_mean), dtype=np.int32)

    cap = int(params.top_rules_per_lag)
    if cap <= 0 or idx.size <= cap:
        return idx

    baseline = 0.01 if mode == "de" else 1.0 - (0.99**27)
    lift = np.log(np.clip(p_mean[idx] / max(baseline, 1e-9), 1e-6, 1e6))
    hit_rate = hits[idx] / np.maximum(1.0, hits[idx].max(initial=1))
    score = (
        lift
        + 0.10 * np.minimum(current_streak[idx], 10)
        + 0.025 * np.minimum(max_streak[idx], 20)
        + 0.08 * np.sqrt(np.clip(hit_rate, 0.0, 1.0))
    )
    keep_local = np.argpartition(score, -cap)[-cap:]
    return idx[keep_local[np.argsort(score[keep_local])[::-1]]]


def fit_paths(
    *,
    df_raw: pd.DataFrame,
    df_2digits: pd.DataFrame,
    params: PathParams,
    mode: Mode,
    anchor_date: Optional[date] = None,
    scope: str = "all",
) -> tuple[list[PathStats], dict[date, np.ndarray], list[date]]:
    """Fit path rules using history up to ``anchor_date`` (inclusive).

    The implementation precomputes every position-pair number once per draw,
    then evaluates each lag with vectorized target lookups.  This is materially
    faster than recomputing all pair numbers inside the day×lag loop.
    """
    df_raw = df_raw.sort_values("date").reset_index(drop=True)
    df_2digits = df_2digits.sort_values("date").reset_index(drop=True)
    dates, targets_loto, targets_de = build_daily_targets(df_2digits)
    if not dates:
        return [], {}, []

    raw_digits = [build_rawdata_digits_from_row(row) for _, row in df_raw.iterrows()]
    raw_matrix = np.stack(raw_digits).astype(np.uint8, copy=False)
    p_count = raw_matrix.shape[1]

    allowed = np.zeros(p_count, dtype=bool)
    allowed[np.asarray(get_scope_indices(scope), dtype=int)] = True
    i_all, j_all = enumerate_position_pairs(p_count)
    pair_mask = allowed[i_all] & allowed[j_all]
    i_idx = i_all[pair_mask]
    j_idx = j_all[pair_mask]

    # days × rules, each entry is the 00..99 number generated by the two positions.
    pair_nums = (10 * raw_matrix[:, i_idx] + raw_matrix[:, j_idx]).astype(np.uint8, copy=False)

    target_loto = np.zeros((len(dates), 100), dtype=bool)
    for t, hitset in enumerate(targets_loto):
        if hitset:
            target_loto[t, np.fromiter(hitset, dtype=np.int16, count=len(hitset))] = True
    target_de = np.asarray(targets_de, dtype=np.uint8)

    special_mask = np.zeros(p_count, dtype=bool)
    special_mask[np.asarray(get_scope_indices("special_only"), dtype=int)] = True
    special_touch = (special_mask[i_idx] | special_mask[j_idx]).astype(np.int8)
    special_both = (special_mask[i_idx] & special_mask[j_idx]).astype(np.int8)

    anchor_idx = _resolve_anchor_index(dates, anchor_date)
    idx_end = anchor_idx
    idx_start = max(0, anchor_idx - params.window_days + 1)

    stats: list[PathStats] = []
    for lag in range(1, params.lag_max + 1):
        target_start = max(idx_start, lag)
        if target_start > idx_end:
            continue
        target_idx = np.arange(target_start, idx_end + 1, dtype=np.int32)
        base_idx = target_idx - lag
        nums = pair_nums[base_idx]

        if mode == "loto":
            day_targets = target_loto[target_idx]
            hit_matrix = np.take_along_axis(day_targets, nums.astype(np.intp), axis=1)
        else:
            hit_matrix = nums == target_de[target_idx, None]

        trials = int(hit_matrix.shape[0])
        hits = hit_matrix.sum(axis=0, dtype=np.int32)
        max_streak, current_streak = _streak_stats(hit_matrix)
        p_mean = (hits + params.alpha) / (trials + params.alpha + params.beta)

        selected = _select_rule_indices(
            p_mean=p_mean,
            hits=hits,
            max_streak=max_streak,
            current_streak=current_streak,
            params=params,
            mode=mode,
        )
        for k in selected:
            stats.append(
                PathStats(
                    lag=lag,
                    i=int(i_idx[k]),
                    j=int(j_idx[k]),
                    trials=trials,
                    hits=int(hits[k]),
                    p_mean=float(p_mean[k]),
                    max_streak=int(max_streak[k]),
                    current_streak=int(current_streak[k]),
                    special_touch=int(special_touch[k]),
                    special_both=int(special_both[k]),
                )
            )

    raw_by_date = {dates[i]: raw_digits[i] for i in range(len(dates))}
    return stats, raw_by_date, dates


def _filter_paths(stats: list[PathStats], params: PathParams, kind: FilterKind) -> list[PathStats]:
    stats = [s for s in stats if s.trials >= params.min_trials]
    if kind == "active":
        return [s for s in stats if s.current_streak >= params.min_current_streak]
    return [s for s in stats if s.max_streak >= params.min_max_streak]


def paths_to_dataframe(stats: list[PathStats]) -> pd.DataFrame:
    return pd.DataFrame(
        [
            {
                "lag": s.lag,
                "i": s.i,
                "j": s.j,
                "trials": s.trials,
                "hits": s.hits,
                "p_mean": s.p_mean,
                "max_streak": s.max_streak,
                "current_streak": s.current_streak,
                "special_touch": s.special_touch,
                "special_both": s.special_both,
            }
            for s in stats
        ]
    )


def _empty_prediction() -> pd.DataFrame:
    return pd.DataFrame(
        {
            "number": np.arange(100, dtype=np.int32),
            "prob": np.zeros(100, dtype=np.float64),
            "support_paths_count": np.zeros(100, dtype=np.int32),
            "evidence_weight": np.zeros(100, dtype=np.float64),
        }
    )


def predict_from_fitted_paths_full(
    *,
    stats: list[PathStats],
    raw_by_date: dict[date, np.ndarray],
    dates: list[date],
    params: PathParams,
    kind: FilterKind,
    mode: Mode = "loto",
    anchor_date: Optional[date] = None,
    scope: str = "all",
    bias_special_touch: float = 1.0,
    bias_special_both: float = 1.0,
) -> pd.DataFrame:
    """Return calibrated-style path evidence for all 00..99 values.

    Path rules are highly correlated because many share digits, lags and source
    draws.  Multiplying their complements (legacy noisy-OR) incorrectly treats
    them as independent and quickly drives probabilities to 1.0.  We instead use
    a reliability-weighted mean and Bayesian shrinkage toward the mode baseline.
    This keeps path output numerically stable and better suited for ensembles.
    """
    if not dates:
        return _empty_prediction()
    if anchor_date is None:
        anchor_date = dates[-1]

    df_stats = paths_to_dataframe(stats)
    if df_stats.empty:
        return _empty_prediction()

    eligible = pd.to_numeric(df_stats["trials"], errors="coerce").fillna(0).astype(int) >= params.min_trials
    if kind == "active":
        eligible &= pd.to_numeric(df_stats["current_streak"], errors="coerce").fillna(0).astype(int) >= params.min_current_streak
    else:
        eligible &= pd.to_numeric(df_stats["max_streak"], errors="coerce").fillna(0).astype(int) >= params.min_max_streak
    paths = df_stats.loc[eligible].copy()
    if paths.empty:
        return _empty_prediction()

    next_date = anchor_date + timedelta(days=1)
    next_numbers = np.full(len(paths), -1, dtype=np.int16)
    for pos, (_, row) in enumerate(paths.iterrows()):
        base_date = next_date - timedelta(days=int(row["lag"]))
        raw = raw_by_date.get(base_date)
        if raw is None:
            continue
        i = int(row["i"])
        j = int(row["j"])
        next_numbers[pos] = int(10 * int(raw[i]) + int(raw[j]))
    paths["next_number"] = next_numbers
    paths = paths[(paths["next_number"] >= 0) & (paths["next_number"] < 100)].copy()
    if paths.empty:
        return _empty_prediction()

    p = paths["p_mean"].astype(float).to_numpy()
    if scope in {"near_special", "special_only"}:
        touched = paths["special_touch"].astype(bool).to_numpy()
        both = paths["special_both"].astype(bool).to_numpy()
        p = np.where(both, p * float(bias_special_both), np.where(touched, p * float(bias_special_touch), p))
    p = np.clip(p, 1e-6, 1 - 1e-6)

    trials = paths["trials"].astype(float).to_numpy()
    reliability = trials / (trials + 120.0)
    if kind == "active":
        streak = np.minimum(paths["current_streak"].astype(float).to_numpy(), 8.0)
        streak_weight = 1.0 + 0.05 * streak
    else:
        streak = np.minimum(paths["max_streak"].astype(float).to_numpy(), 15.0)
        streak_weight = 1.0 + 0.02 * streak
    weights = reliability * streak_weight

    nums = paths["next_number"].astype(int).to_numpy()
    support = np.bincount(nums, minlength=100).astype(np.int32)
    weight_sum = np.bincount(nums, weights=weights, minlength=100).astype(np.float64)
    weighted_p = np.bincount(nums, weights=weights * p, minlength=100).astype(np.float64)

    baseline = 0.01 if mode == "de" else 1.0 - (0.99**27)
    prior_strength = 6.0
    prob = (weighted_p + prior_strength * baseline) / (weight_sum + prior_strength)
    prob = np.where(support > 0, prob, baseline)
    if mode == "de":
        prob = prob / max(float(prob.sum()), 1e-12)

    return pd.DataFrame(
        {
            "number": np.arange(100, dtype=np.int32),
            "prob": prob,
            "support_paths_count": support,
            "evidence_weight": weight_sum,
        }
    )


def predict_from_fitted_paths(
    *,
    stats: list[PathStats],
    raw_by_date: dict[date, np.ndarray],
    dates: list[date],
    params: PathParams,
    kind: FilterKind,
    mode: Mode = "loto",
    top_numbers: int = 20,
    anchor_date: Optional[date] = None,
    scope: str = "all",
    bias_special_touch: float = 1.0,
    bias_special_both: float = 1.0,
) -> pd.DataFrame:
    out = predict_from_fitted_paths_full(
        stats=stats,
        raw_by_date=raw_by_date,
        dates=dates,
        params=params,
        kind=kind,
        mode=mode,
        anchor_date=anchor_date,
        scope=scope,
        bias_special_touch=bias_special_touch,
        bias_special_both=bias_special_both,
    )
    out = out[out["support_paths_count"] > 0].sort_values(
        ["prob", "evidence_weight", "support_paths_count"], ascending=[False, False, False]
    )
    return out.head(top_numbers).reset_index(drop=True)


def predict_next_day_full(
    *,
    df_raw: pd.DataFrame,
    df_2digits: pd.DataFrame,
    params: PathParams,
    mode: Mode,
    kind: FilterKind,
    top_numbers: int = 20,
    anchor_date: Optional[date] = None,
    scope: str = "all",
    bias_special_touch: float = 1.0,
    bias_special_both: float = 1.0,
) -> pd.DataFrame:
    stats, raw_by_date, dates = fit_paths(
        df_raw=df_raw, df_2digits=df_2digits, params=params, mode=mode, anchor_date=anchor_date, scope=scope
    )
    return predict_from_fitted_paths_full(
        stats=stats,
        raw_by_date=raw_by_date,
        dates=dates,
        params=params,
        kind=kind,
        mode=mode,
        anchor_date=anchor_date,
        scope=scope,
        bias_special_touch=bias_special_touch,
        bias_special_both=bias_special_both,
    )


def predict_next_day(
    *,
    df_raw: pd.DataFrame,
    df_2digits: pd.DataFrame,
    params: PathParams,
    mode: Mode,
    kind: FilterKind,
    top_numbers: int = 20,
    anchor_date: Optional[date] = None,
    scope: str = "all",
    bias_special_touch: float = 1.0,
    bias_special_both: float = 1.0,
) -> pd.DataFrame:
    stats, raw_by_date, dates = fit_paths(
        df_raw=df_raw, df_2digits=df_2digits, params=params, mode=mode, anchor_date=anchor_date, scope=scope
    )
    return predict_from_fitted_paths(
        stats=stats,
        raw_by_date=raw_by_date,
        dates=dates,
        params=params,
        kind=kind,
        mode=mode,
        top_numbers=top_numbers,
        anchor_date=anchor_date,
        scope=scope,
        bias_special_touch=bias_special_touch,
        bias_special_both=bias_special_both,
    )
